package com.drivinglicenseapk.handling


import com.drivinglicenseapk.R

class QuestionData {

    var ifExamEnded = 0

    val questionStrings = arrayOf(
        "Sinjali në figurë, si rregull, në rrugë interurbane është 150 metër para pjesës ku fillon deformimi i rrugës.",
        "Sinjali në figurë paralajmëron një pjesë rruge të deformuar",
        "Në prani të sinjalit në figurë duhet të lëvizet me kujdes, sidomos kur rruga është e rrëshqitshme.",
        "Sinjali në figurë paralajmëron një pjerrësi të rrezikshme.",
        "Sinjali në figurë paralajmëron një ndryshim të fortë të pjerrësisë së rrugës",
        "Sinjali në figurë paralajmëron një kthesë të dyfishtë",
        "Sinjali si në figurë paralajmëron rrugë të deformuar pas një distance prej 320 metër.",
        "Sinjali si në figurë paralajmëron rrugë të deformuar për shkak të punimeve.",
        "Sinjali në figurë është një sinjal vertikal që paralajmëron rrezik.",
        "Sinjali në figurë paralajmëron një pjesë rruge me fushëpamje të kufizuar.",
        "Sinjali në figurë paralajmëron një pjesë rruge që është në formë kurrizi.",
        "Sinjali në figurë paralajmëron një pjesë rruge që është në ngjitje dhe pastaj në zbritje.",
        "Në prani të sinjalit në figurë, në një rrugë me një korsi për çdo sens lëvizje, ndalohet parakalimi në pjesën e përpjetë të rrugës.",
        "Në prani të sinjalit në figurë ndalohet qëndrimi i mjetit në pjesën ngjitëse dhe zbritëse të rrugës.",
        "Në prani të sinjalit në figurë, në një rrugë me një korsi për çdo sens lëvizje, duhet të ulni shpejtësinë dhe të spostoheni në anën e djathtë të karrexhatës.",
        "Sinjali në figurë paralajmëron një pjesë rruge të deformuar",
        "Sinjali në figurë paralajmëron një pjesë rruge të dëmtuar.",
        "Sinjali në figurë, ndalon parakalimin ne ngjitje dhe zbritje te kurrizit.",
        "Sinjali në figurë paralajmëron punime në rrugë.",
        "Sinjali në figurë është një sinjal vertikal që paralajmëron rrezik.",
        "Sinjali në figurë paralajmëron një pjesë rruge në formë të lugët (zbritje dhe ngjitje).",
        "Në prani të sinjalit në figurë lejohet parakalimi, por me kujdes dhe sipas rregullave.",
        "Sinjali në figurë paralajmëron mundësinë e formimit të pellgjeve të ujit në raste shiu.",
        "Në prani të sinjalit në figurë duhet të zvogëlojmë shpejtësinë e lëvizjes për shkak të formës së lugët të rrugës.",
        "Sinjali në figurë paralajmëron bankina rrugore të dëmtuara.",
        "Sinjali në figurë paralajmëron një pjesë rruge të dëmtuar.",
        "Sinjali në figurë paralajmëron një rrugë me gjendje të keqe të asfaltit.",
        "Sinjali në figurë paralajmëron një ngushtim të karrexhatës.",
        "Sinjali në figurë paralajmëron një kthesë të rrezikshme, djathtas.",
        "Në prani të sinjalit në figurë ndalohet ndryshimi i sensit të lëvizjes së mjetit.",
        "Në prani të sinjalit në figurë ndalohet qëndrimi apo pushimi i mjetit.",
        "Sinjali në figurë ndalon lëvizjen prapa (indietro).",
        "Në prani të sinjalit në figurë duhet të rrisim shpejtësinë e lëvizjes.",
        "Sinjali në figurë paralajmëron disa kthesa, ku e para fillon nga e djathta.",
        "Në prani të sinjalit në figurë lejohet pushimi i mjetit në kthesë.",
        "Sinjali në figurë paralajmëron një degëzim dhe detyron kthimin djathtas.",
        "Sinjali në figurë paralajmëron ndryshim korsie",
        "Në prani të sinjalit në figurë lejohet parakalimi i mjeteve edhe pse rruga është e ngushtë.",
        "Sinjali në figurë është një sinjal vertikal që paralajmëron rrezik.",
        "Sinjali në figurë, si rregull, në rrugë interurbane është i vendosur 150 metër para kthesës së rrezikshme.",
        "Sinjali në figurë paralajmëron një kthesë të rrezikshme, majtas.",
        "Në prani të sinjalit në figurë duhet zvogëluar shpejtësia e lëvizjes së mjetit.",
        "Në prani të sinjalit në figurë ndalohet ndryshimi i sensit të lëvizjes.",
        "Në prani të sinjalit në figurë ndalohet qëndrimi i mjetit në kthesë.",
        "Në prani të sinjalit në figurë ndalohet lëvizja prapa (indietro).",
        "Sinjali në figurë paralajmëron rënie gurësh nga e djathta.",
        "Sinjali në figurë lejon ndryshimin e sensit të lëvizjes.",
        "Sinjali në figurë paralajmëron ngushtimin e rrugës nga krahu i majtë.",
        "Sinjali në figurë paralajmëron se po i afrohemi një rrethqarkullimi.",
        //6
    )
    val noImage = R.drawable.img_overall
    val questionImages = arrayOf(
        R.drawable.img_0,
        R.drawable.img_0,
        R.drawable.img_0,
        R.drawable.img_0,
        R.drawable.img_0,
        R.drawable.img_0,
        R.drawable.img_1,
        R.drawable.img_2,
        R.drawable.img_3,
        R.drawable.img_3,
        R.drawable.img_3,
        R.drawable.img_3,
        R.drawable.img_3,
        R.drawable.img_3,
        R.drawable.img_3,
        R.drawable.img_3,
        R.drawable.img_3,
        R.drawable.img_3,
        R.drawable.img_3,
        R.drawable.img_4,
        R.drawable.img_4,
        R.drawable.img_4,
        R.drawable.img_4,
        R.drawable.img_4,
        R.drawable.img_4,
        R.drawable.img_4,
        R.drawable.img_4,
        R.drawable.img_4,
        R.drawable.img_5,
        R.drawable.img_5,
        R.drawable.img_5,
        R.drawable.img_5,
        R.drawable.img_5,
        R.drawable.img_5,
        R.drawable.img_5,
        R.drawable.img_5,
        R.drawable.img_5,
        R.drawable.img_5,
        R.drawable.img_6,
        R.drawable.img_6,
        R.drawable.img_6,
        R.drawable.img_6,
        R.drawable.img_6,
        R.drawable.img_6,
        R.drawable.img_6,
        R.drawable.img_6,
        R.drawable.img_6,
        R.drawable.img_6,
        R.drawable.img_6,

    )
    val questionAnswers = arrayOf(
        "Sakte",
        "Sakte",
        "Sakte",
        "Gabim",
        "Gabim",
        "Gabim",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Gabim",
        "Gabim",
        "Gabim",
        "Gabim",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Gabim",
        "Gabim",
        "Gabim",
        "Gabim",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Gabim",
        "Gabim",
        "Gabim",
        "Gabim",
        "Gabim",
        "Gabim",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Gabim",
        "Gabim",
        "Gabim",
        "Gabim",

    )
}