package com.drivinglicenseapk.handling


import com.drivinglicenseapk.R

class QuestionData {

    val questionStrings = arrayOf(
        //1//
        "Sinjali në figurë, si rregull, në rrugë interurbane është 150 metër para pjesës ku fillon deformimi i rrugës.",
        "Sinjali në figurë paralajmëron një pjesë rruge të deformuar.",
        "Në prani të sinjalit në figurë duhet të lëvizet me kujdes, sidomos kur rruga është e rrëshqitshme.",
        "Sinjali në figurë paralajmëron një pjerrësi të rrezikshme.",
        "Sinjali në figurë paralajmëron një ndryshim të fortë të pjerrësisë së rrugës.",
        "Sinjali në figurë paralajmëron një kthesë të dyfishtë",
        //1-1//
        "Sinjali si në figurë paralajmëron rrugë të deformuar pas një distance prej 320 metër.",
        //1-2//
        "Sinjali si në figurë paralajmëron rrugë të deformuar për shkak të punimeve.",
        //2//
        "Sinjali në figurë është një sinjal vertikal që paralajmëron rrezik.",
        "Sinjali në figurë paralajmëron një pjesë rruge me fushëpamje të kufizuar.",
        "Sinjali në figurë paralajmëron një pjesë rruge që është në formë kurrizi.",
        "Sinjali në figurë paralajmëron një pjesë rruge që është në ngjitje dhe pastaj në zbritje",
        "Në prani të sinjalit në figurë, në një rrugë me një korsi për çdo sens lëvizje, ndalohet parakalimi në pjesën e përpjetë të rrugës.",
        "Në prani të sinjalit në figurë ndalohet qëndrimi i mjetit në pjesën ngjitëse dhe zbritëse të rrugës.",
        "Në prani të sinjalit në figurë, në një rrugë me një korsi për çdo sens lëvizje, duhet të ulni shpejtësinë dhe të spostoheni në anën e djathtë të karrexhatës.",
        "Sinjali në figurë paralajmëron një pjesë rruge të deformuar.",
        "Sinjali në figurë paralajmëron një pjesë rruge të dëmtuar.",
        "Sinjali në figurë, ndalon parakalimin ne ngjitje dhe zbritje te kurrizit.",
        "Sinjali në figurë paralajmëron punime në rrugë.",
        //3//
        "Sinjali në figurë është një sinjal vertikal që paralajmëron rrezik.",
        "Sinjali në figurë paralajmëron një pjesë rruge në formë të lugët (zbritje dhe ngjitje).",
        "Në prani të sinjalit në figurë lejohet parakalimi, por me kujdes dhe sipas rregullave",
        "Sinjali në figurë paralajmëron mundësinë e formimit të pellgjeve të ujit në raste shiu.",
        "Në prani të sinjalit në figurë duhet të zvogëlojmë shpejtësinë e lëvizjes për shkak të formës së lugët të rrugës",
        "Sinjali në figurë paralajmëron bankina rrugore të dëmtuara.",
        "Sinjali në figurë paralajmëron një pjesë rruge të dëmtuar.",
        "Sinjali në figurë paralajmëron një rrugë me gjendje të keqe të asfaltit.",
        "Sinjali në figurë paralajmëron një ngushtim të karrexhatës.",
        //4//
        "Sinjali në figurë paralajmëron një kthesë të rrezikshme, djathtas.",
        "Në prani të sinjalit në figurë ndalohet ndryshimi i sensit të lëvizjes së mjetit.",
        "Në prani të sinjalit në figurë ndalohet qëndrimi apo pushimi i mjetit.",
        "Sinjali në figurë ndalon lëvizjen prapa (indietro).",
        "Në prani të sinjalit në figurë duhet të rrisim shpejtësinë e lëvizjes.",
        "Sinjali në figurë paralajmëron disa kthesa, ku e para fillon nga e djathta.",
        "Në prani të sinjalit në figurë lejohet pushimi i mjetit në kthesë.",
        "Sinjali në figurë paralajmëron një degëzim dhe detyron kthimin djathtas. G",
        "Sinjali në figurë paralajmëron ndryshim korsie.",
        "Në prani të sinjalit në figurë lejohet parakalimi i mjeteve edhe pse rruga është e ngushtë.",
        //5//
        "Sinjali në figurë është një sinjal vertikal që paralajmëron rrezik.",
        "Sinjali në figurë, si rregull, në rrugë interurbane është i vendosur 150 metër para kthesës së rrezikshme.",
        "Sinjali në figurë paralajmëron një kthesë të rrezikshme, majtas.",
        "Në prani të sinjalit në figurë duhet zvogëluar shpejtësia e lëvizjes së mjetit.",
        "Në prani të sinjalit në figurë ndalohet ndryshimi i sensit të lëvizjes.",
        "Në prani të sinjalit në figurë ndalohet qëndrimi i mjetit në kthesë.",
        "Në prani të sinjalit në figurë ndalohet lëvizja prapa (indietro).",
        "Sinjali në figurë paralajmëron rënie gurësh nga e djathta.",
        "Sinjali në figurë lejon ndryshimin e sensit të lëvizjes.",
        "Sinjali në figurë paralajmëron ngushtimin e rrugës nga krahu i majtë.",
        "Sinjali në figurë paralajmëron se po i afrohemi një rrethqarkullimi.",
        //6//
        "Sinjali në figurë paralajmëron kthesa të rrezikshme dhe të njëpasnjëshme, prej të cilave kthesa e parë është djathtas.",
        "Në prani të sinjalit në figurë duhet zvogëluar shpejtësia e lëvizjes së mjetit.",
        "Në prani të sinjalit në figurë ndalohet ndryshimi i sensit të lëvizjes së mjetit.",
        "Në prani të sinjalit në figurë ndalohet qëndrimi apo pushimi i mjetit në kthesa.",
        "Në prani të sinjalit si në figurë ndalohet lëvizja prapa (indietro).",
        "Në prani të sinjalit në figurë lejohet parakalimi i mjeteve në rrugë me një korsi për sens lëvizje.",
        "Sinjali në figurë paralajmëron devijim të rrugës për shkak të punimeve në rrugë.",
        "Sinjali në figurë paralajmëron një pjerrësi të rrezikshme.",
        "Në prani të sinjalit në figurë lejohet të kryhet manovra e lëvizjes mbrapa.",
        "Në prani të sinjalit në figurë lejohet qëndrimi i mjetit edhe në kthesë",
        //6-1//
        "Sinjali në figurë paralajmëron 3 (tre) kthesa të rrezikshme prej të cilave e para është djathtas.",
        //7//
        "Sinjali në figurë, si rregull, në rrugë interurbane është 150 metër para fillimit të kthesave",
        "Sinjali në figurë paralajmëron kthesa të rrezikshme dhe të njëpasnjëshme, prej të cilave kthesa e parë është majtas.",
        "Sinjali në figurë paralajmëron kthesa me dukshmëri të kufizuar.",
        "Në prani të sinjalit në figurë duhet zvogëluar shpejtësia e lëvizjes së mjetit duke e përshtatur atë me fushëpamjen.",
        "Në prani të sinjalit në figurë, në rrugë me dy sense lëvizje dhe me një korsi për sens, duhet të tregohet kujdes kur këmbehemi me një mjet tjetër.",
        "Sinjali në figurë paralajmëron dy kthesa për shkak të punimeve në rrugë.",
        "Sinjali në figurë paralajmëron dy kurrize rrugore.",
        "Sinjali në figurë paralajmëron një pjerrësi të rrezikshme.",
        "Sinjali në figurë tregon hyrje ne një tunel.",
        "Sinjali në figurë lejon qëndrimin e mjetit në çdo pjesë të rrugës.",
        "Sinjali në figurë kërkon uljen e shpejtësisë vetëm para kthesës së parë.",
        //8//
        "Sinjali në figurë është një sinjal vertikal që paralajmëron rrezik.",
        "Sinjali në figurë paralajmëron një kalim në nivel të ruajtur me barriera ose me gjysmëbarriera",
        "Sinjali në figurë paralajmëron kalim në nivel pranë të cilit ka drita të kuqe dhe aparate akustikë.",
        "Në prani të sinjalit në figurë duhet zvogëluar shpejtësia e lëvizjes së mjetit",
        "Sinjali në figurë paralajmëron ndërprerjen e rrugës me një linjë hekurudhore.",
        "Në prani të sinjalit në figurë ndalohet qëndrimi i mjetit në afërsi ose përgjatë kalimit në nivel.",
        "Sinjali në figurë paralajmëron një kalim në nivel, të paruajtur me barriera ose me gjysmëbarriera.",
        "Sinjali në figurë paralajmëron se jemi në afërsi të një stacioni treni me disa linja hekurudhore.",
        "Sinjali në figurë paralajmëron se rruga në vazhdim është e mbyllur.",
        "Sinjali në figurë paralajmëron një rrugë me një karrexhatë dhe me tri korsi lëvizjeje.",
        //9//
        "Sinjali në figurë është sinjal vertikal rreziku.",
        "Sinjali në figurë paralajmëron ndërprerjen e rrugës me një linjë hekurudhore të pambrojtur",
        "Në prani të sinjalit në figurë drejtuesit e mjeteve duhet të rrisin kujdesin në drejtimin e mjetit.",
        "Sinjali në figurë paralajmëron kalim në nivel të pa mbrojtur.",
        "Në prani të sinjalit në figurë ndalohet qëndrimi i mjetit si në afërsi ashtu dhe përgjatë kalimit në nivel pa pengesa.",
        "Në prani të sinjalit në figurë duhet të sigurohemi si nga e djathta dhe nga e majta, para se të kapërcejmë linjën hekurudhore.",
        "Në prani të sinjalit në figurë duhet të tregojmë kujdes për të shmangur përplasjen me trenin.",
        "Sinjali në figurë paralajmëron kryqëzim të linjave hekurudhore me njëra-tjetrën.",
        "Sinjali në figurë paralajmëron një kalim në nivel, të pajisur me gjysmëbarriera.",
        "Sinjali në figurë paralajmëron një ndërprerje të rrugës me një linjë hekurudhore të mbrojtur me barriera.",
        //10//

    )
    val noImage = R.drawable.img_overall
    val questionImages = arrayOf(
        //1
        R.drawable.img_1,
        R.drawable.img_1,
        R.drawable.img_1,
        R.drawable.img_1,
        R.drawable.img_1,
        R.drawable.img_1,
        //1-1//
        R.drawable.img_1_1,
        //1-2//
        R.drawable.img_1_2,
        //2//
        R.drawable.img_2,
        R.drawable.img_2,
        R.drawable.img_2,
        R.drawable.img_2,
        R.drawable.img_2,
        R.drawable.img_2,
        R.drawable.img_2,
        R.drawable.img_2,
        R.drawable.img_2,
        R.drawable.img_2,
        R.drawable.img_2,
        //3//
        R.drawable.img_3,
        R.drawable.img_3,
        R.drawable.img_3,
        R.drawable.img_3,
        R.drawable.img_3,
        R.drawable.img_3,
        R.drawable.img_3,
        R.drawable.img_3,
        R.drawable.img_3,
        //4//
        R.drawable.img_4,
        R.drawable.img_4,
        R.drawable.img_4,
        R.drawable.img_4,
        R.drawable.img_4,
        R.drawable.img_4,
        R.drawable.img_4,
        R.drawable.img_4,
        R.drawable.img_4,
        R.drawable.img_4,
        //5//
        R.drawable.img_5,
        R.drawable.img_5,
        R.drawable.img_5,
        R.drawable.img_5,
        R.drawable.img_5,
        R.drawable.img_5,
        R.drawable.img_5,
        R.drawable.img_5,
        R.drawable.img_5,
        R.drawable.img_5,
        R.drawable.img_5,
        //6//
        R.drawable.img_6,
        R.drawable.img_6,
        R.drawable.img_6,
        R.drawable.img_6,
        R.drawable.img_6,
        R.drawable.img_6,
        R.drawable.img_6,
        R.drawable.img_6,
        R.drawable.img_6,
        R.drawable.img_6,
        //6-1//
        R.drawable.img_6_1,
        //7//
        R.drawable.img_7,
        R.drawable.img_7,
        R.drawable.img_7,
        R.drawable.img_7,
        R.drawable.img_7,
        R.drawable.img_7,
        R.drawable.img_7,
        R.drawable.img_7,
        R.drawable.img_7,
        R.drawable.img_7,
        R.drawable.img_7,
        //8//
        R.drawable.img_8,
        R.drawable.img_8,
        R.drawable.img_8,
        R.drawable.img_8,
        R.drawable.img_8,
        R.drawable.img_8,
        R.drawable.img_8,
        R.drawable.img_8,
        R.drawable.img_8,
        R.drawable.img_8,
        //9//
        R.drawable.img_9,
        R.drawable.img_9,
        R.drawable.img_9,
        R.drawable.img_9,
        R.drawable.img_9,
        R.drawable.img_9,
        R.drawable.img_9,
        R.drawable.img_9,
        R.drawable.img_9,
        R.drawable.img_9,
        //10//


    )
    val questionAnswers = arrayOf(
        //1//
        "Sakte",
        "Sakte",
        "Sakte",
        "Gabim",
        "Gabim",
        "Gabim",
        //1-1//
        "Sakte",
        //1-2//
        "Sakte",
        //2//
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        //3//
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Gabim",
        "Gabim",
        "Gabim",
        "Gabim",
        //4//
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Gabim",
        "Gabim",
        "Gabim",
        "Gabim",
        "Gabim",
        "Gabim",
        //5//
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Gabim",
        "Gabim",
        "Gabim",
        "Gabim",
        //6//
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Gabim",
        "Gabim",
        "Gabim",
        "Gabim",
        "Gabim",
        //6-1//
        "Sakte",
        //7//
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Gabim",
        "Gabim",
        "Gabim",
        "Gabim",
        "Gabim",
        "Gabim",
        //8//
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Gabim",
        "Gabim",
        "Gabim",
        "Gabim",
        //9//
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Sakte",
        "Gabim",
        "Gabim",
        "Gabim",
        //10//



    )
}